services:
  wmata-rail-positions:
    container_name: wmata-rail-positions-python
    tty: true
    environment:
      CONFIG_SECRETS_FILE: /run/secrets/config_secrets
      PYTHONUNBUFFERED: 1
    image: wmata-rail-positions-python
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    secrets:
      - config_secrets
secrets:
  config_secrets:
    file: ./config/.secrets.toml
