# Elastic Server Configuration
ES_USERNAME = "elastic"
ES_PASSWORD = "eOHt7mLwh7CmCZM1B2HQs8Qp"
ES_URL = "https://myoung-demo.es.us-east-1.aws.found.io:443"
KB_URL = "https://myoung-demo.kb.us-east-1.aws.found.io:9243"

# APM Configuration
APM_SECRET_TOKEN = "vhPXpsiARJ3Ogc5dO6"
APM_SERVER_URL = "https://myoung-demo.apm.us-east-1.aws.found.io:443"

# WMATA Configuration
WMATA_API_KEY = "acd9c07bf6f54998ae7024547d88c4b1"
